pipeline {
    agent any

    environment {
        cluster = "DeployClusterAWS"
        service = "DeployClusterService"
    }

    stages {
        stage('Deploy to Prod ecs') {
          steps {
        withAWS(credentials: 'AWS-Cred', region: 'ap-south-1') {
          sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
        }
      }
     }

    }
}